services:
  - type: web
    name: asmita-backend
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: WEB_CONCURRENCY
        value: 4
